CREATE DATABASE QLSACH
GO

USE QLSACH
GO

CREATE TABLE CATEGORYBOOK(
	CATEGORYID INT PRIMARY KEY,
	CATEGORYNAME NVARCHAR(255) NOT NULL
);

CREATE TABLE BOOKS(
	BOOKID CHAR(6) NOT NULL,
	BOOKNAME NVARCHAR(255) NOT NULL,
	NAMXB INT NOT NULL, 
	PRIMARY KEY (BOOKID),
	CATEGORYID INT,
	FOREIGN KEY (CATEGORYID) REFERENCES CATEGORYBOOK (CATEGORYID)
);


INSERT INTO CATEGORYBOOK(CATEGORYID, CATEGORYNAME)
VALUES
	(1, N'Công Nghệ Thông Tin'),
	(2, N'Ngôn Ngữ Anh'),
	(3, N'Quản Trị Kinh Doanh');

INSERT INTO BOOKS(BOOKID, BOOKNAME, NAMXB, CATEGORYID)
VALUES 
	('BOOK01', N'Công Nghệ Phần Mềm', 2015,1),
	('BOOK02', N'Hệ Thống Thông Tin', 2015,1),
	('BOOK03', N'An Toàn Thông Tin', 2015,1),
	('BOOK04', N'Tiếng Anh Thương Mại', 2015,2),
	('BOOK05', N'Tiếng Anh Truyền Thống', 2015,2),
	('BOOK06', N'Kế Toán Doanh Nghiệp', 2015,3);